server:
  port: 8080

spring:
  application:
    name: fund
  datasource:
    url: jdbc:oracle:thin:@//avdf01.rh:1985/rayansite.rh
    username: support_fund
    password: S$EAB6BF13
    driver-class-name: oracle.jdbc.OracleDriver
    minimum-idle: 2
    maximum-pool-size: 10
    connection-timeout: 150000
    idle-timeout: 150000
    initialization-fail-timeout: 150000
