server:
  port: 8080


spring:
  datasource:
    url: jdbc:oracle:thin:@//avdf01.rh:1985/rayansite.rh
    username: support_fund
    password: S$EAB6BF13
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: false
    show-manual-log: true
  tenant-datasource:
    minimum-idle: 2
    maximum-pool-size: 10
    connection-timeout: 150000
    idle-timeout: 150000
    initialization-fail-timeout: 150000


redis:
#  port: 6379
  port: 63799
  size: 512mb
  host: 127.0.0.1

springdoc:
  swagger-ui:
    server-url: http://localhost:${server.port}
    path: /swagger-ui/index.html
    enabled: true
    disable-swagger-default-url: true
